# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/imjustabill/pack-my-sprites

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/imjustabill/pack-my-sprites

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imjustabill/pack-my-sprites/CMakeFiles /home/imjustabill/pack-my-sprites/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/imjustabill/pack-my-sprites/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named utest

# Build rule for target.
utest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utest
.PHONY : utest

# fast build rule for target.
utest/fast:
	$(MAKE) -f modules/utest/CMakeFiles/utest.dir/build.make modules/utest/CMakeFiles/utest.dir/build
.PHONY : utest/fast

#=============================================================================
# Target rules for targets named pms_files

# Build rule for target.
pms_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_files
.PHONY : pms_files

# fast build rule for target.
pms_files/fast:
	$(MAKE) -f modules/files/CMakeFiles/pms_files.dir/build.make modules/files/CMakeFiles/pms_files.dir/build
.PHONY : pms_files/fast

#=============================================================================
# Target rules for targets named files-is_fully_qualified-test

# Build rule for target.
files-is_fully_qualified-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 files-is_fully_qualified-test
.PHONY : files-is_fully_qualified-test

# fast build rule for target.
files-is_fully_qualified-test/fast:
	$(MAKE) -f modules/files/tests/CMakeFiles/files-is_fully_qualified-test.dir/build.make modules/files/tests/CMakeFiles/files-is_fully_qualified-test.dir/build
.PHONY : files-is_fully_qualified-test/fast

#=============================================================================
# Target rules for targets named pms_gimp

# Build rule for target.
pms_gimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_gimp
.PHONY : pms_gimp

# fast build rule for target.
pms_gimp/fast:
	$(MAKE) -f modules/gimp/CMakeFiles/pms_gimp.dir/build.make modules/gimp/CMakeFiles/pms_gimp.dir/build
.PHONY : pms_gimp/fast

#=============================================================================
# Target rules for targets named pms_packing

# Build rule for target.
pms_packing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_packing
.PHONY : pms_packing

# fast build rule for target.
pms_packing/fast:
	$(MAKE) -f modules/packing/CMakeFiles/pms_packing.dir/build.make modules/packing/CMakeFiles/pms_packing.dir/build
.PHONY : pms_packing/fast

#=============================================================================
# Target rules for targets named pms_resources

# Build rule for target.
pms_resources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_resources
.PHONY : pms_resources

# fast build rule for target.
pms_resources/fast:
	$(MAKE) -f modules/resources/CMakeFiles/pms_resources.dir/build.make modules/resources/CMakeFiles/pms_resources.dir/build
.PHONY : pms_resources/fast

#=============================================================================
# Target rules for targets named resources-image-test

# Build rule for target.
resources-image-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 resources-image-test
.PHONY : resources-image-test

# fast build rule for target.
resources-image-test/fast:
	$(MAKE) -f modules/resources/tests/CMakeFiles/resources-image-test.dir/build.make modules/resources/tests/CMakeFiles/resources-image-test.dir/build
.PHONY : resources-image-test/fast

#=============================================================================
# Target rules for targets named pms_layout

# Build rule for target.
pms_layout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_layout
.PHONY : pms_layout

# fast build rule for target.
pms_layout/fast:
	$(MAKE) -f modules/layout/CMakeFiles/pms_layout.dir/build.make modules/layout/CMakeFiles/pms_layout.dir/build
.PHONY : pms_layout/fast

#=============================================================================
# Target rules for targets named layout-build-test

# Build rule for target.
layout-build-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 layout-build-test
.PHONY : layout-build-test

# fast build rule for target.
layout-build-test/fast:
	$(MAKE) -f modules/layout/tests/CMakeFiles/layout-build-test.dir/build.make modules/layout/tests/CMakeFiles/layout-build-test.dir/build
.PHONY : layout-build-test/fast

#=============================================================================
# Target rules for targets named layout-atlas-page-test

# Build rule for target.
layout-atlas-page-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 layout-atlas-page-test
.PHONY : layout-atlas-page-test

# fast build rule for target.
layout-atlas-page-test/fast:
	$(MAKE) -f modules/layout/tests/CMakeFiles/layout-atlas-page-test.dir/build.make modules/layout/tests/CMakeFiles/layout-atlas-page-test.dir/build
.PHONY : layout-atlas-page-test/fast

#=============================================================================
# Target rules for targets named pms_generators

# Build rule for target.
pms_generators: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_generators
.PHONY : pms_generators

# fast build rule for target.
pms_generators/fast:
	$(MAKE) -f modules/generators/CMakeFiles/pms_generators.dir/build.make modules/generators/CMakeFiles/pms_generators.dir/build
.PHONY : pms_generators/fast

#=============================================================================
# Target rules for targets named pms_serialization

# Build rule for target.
pms_serialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_serialization
.PHONY : pms_serialization

# fast build rule for target.
pms_serialization/fast:
	$(MAKE) -f modules/serialization/CMakeFiles/pms_serialization.dir/build.make modules/serialization/CMakeFiles/pms_serialization.dir/build
.PHONY : pms_serialization/fast

#=============================================================================
# Target rules for targets named pms_app

# Build rule for target.
pms_app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms_app
.PHONY : pms_app

# fast build rule for target.
pms_app/fast:
	$(MAKE) -f modules/app/CMakeFiles/pms_app.dir/build.make modules/app/CMakeFiles/pms_app.dir/build
.PHONY : pms_app/fast

#=============================================================================
# Target rules for targets named auto-pack-my-sprites

# Build rule for target.
auto-pack-my-sprites: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 auto-pack-my-sprites
.PHONY : auto-pack-my-sprites

# fast build rule for target.
auto-pack-my-sprites/fast:
	$(MAKE) -f apps/CMakeFiles/auto-pack-my-sprites.dir/build.make apps/CMakeFiles/auto-pack-my-sprites.dir/build
.PHONY : auto-pack-my-sprites/fast

#=============================================================================
# Target rules for targets named pack-my-sprites

# Build rule for target.
pack-my-sprites: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pack-my-sprites
.PHONY : pack-my-sprites

# fast build rule for target.
pack-my-sprites/fast:
	$(MAKE) -f apps/CMakeFiles/pack-my-sprites.dir/build.make apps/CMakeFiles/pack-my-sprites.dir/build
.PHONY : pack-my-sprites/fast

#=============================================================================
# Target rules for targets named pms-man

# Build rule for target.
pms-man: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pms-man
.PHONY : pms-man

# fast build rule for target.
pms-man/fast:
	$(MAKE) -f docs/man/CMakeFiles/pms-man.dir/build.make docs/man/CMakeFiles/pms-man.dir/build
.PHONY : pms-man/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... uninstall"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... utest"
	@echo "... pms_files"
	@echo "... files-is_fully_qualified-test"
	@echo "... pms_gimp"
	@echo "... pms_packing"
	@echo "... pms_resources"
	@echo "... resources-image-test"
	@echo "... pms_layout"
	@echo "... layout-build-test"
	@echo "... layout-atlas-page-test"
	@echo "... pms_generators"
	@echo "... pms_serialization"
	@echo "... pms_app"
	@echo "... auto-pack-my-sprites"
	@echo "... pack-my-sprites"
	@echo "... pms-man"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

